"""Embed the prose documentation in the vestal binary.

`vestal docs <topic>` prints Markdown compiled into the binary, so an agent
with only `vestal` has everything. This turns AGENTS.md (topic `agents`),
docs/reference/<topic>.md and the guides in docs/guide/<topic>.md into Sources/VestalCore/Generated/EmbeddedDocs.swift,
one string literal per topic. The output is committed; a test
(EmbeddedDocsTests) fails when it drifts from the Markdown, so run this after
editing any of those files.

usage: python3 nix/gen-docs.py [repository root]   (default: the parent of nix/)
"""

import pathlib
import re
import sys

HEADER = """\
// Generated by nix/gen-docs.py from AGENTS.md, docs/reference/*.md and docs/guide/*.md.
// Do not edit: change the Markdown and run `python3 nix/gen-docs.py`.

/// The prose topics of `vestal docs`, by name, as written in the Markdown.
public enum EmbeddedDocs {
    public static let topics: [String: String] = [
"""


def literal(text):
    """A Swift raw multi-line string literal whose value is exactly `text`."""
    # Enough '#' that neither the closing delimiter nor an interpolation
    # (\\#...) can appear inside.
    runs = [len(m.group(1)) for m in re.finditer(r'(?:"""|\\)(#+)', text)]
    hashes = "#" * (max(runs, default=0) + 1)
    # The line break before the closing delimiter is not part of the value.
    return f'{hashes}"""\n{text}\n"""{hashes}'


def main():
    root = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parent.parent
    topics = {"agents": root / "AGENTS.md"}
    for folder in ("reference", "guide"):
        for path in sorted((root / "docs" / folder).glob("*.md")):
            if path.stem in topics:
                sys.exit(f"{path}: topic {path.stem} exists twice")
            topics[path.stem] = path
    out = [HEADER]
    for name in sorted(topics):
        text = topics[name].read_text(encoding="utf-8")
        if "\r" in text:
            sys.exit(f"{topics[name]}: carriage returns are not allowed")
        out.append(f'        "{name}": {literal(text)},\n')
    out.append("    ]\n}\n")
    target = root / "Sources" / "VestalCore" / "Generated" / "EmbeddedDocs.swift"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()
