"""Generate Sources/VestalCore/Generated/IconMap.swift from the vendored
Phosphor metadata (Resources/icons/regular.css and fill.css).

usage: gen-iconmap.py [repo root]   (default: the parent of this script's directory)
Also writes web/renderer/icons.js for the web renderer.

Each CSS rule `.ph.ph-<name>:before { content: "\\eXXX"; }` (and
`.ph-fill.ph-<name>:before` in fill.css) gives an icon's code point in that
weight. The Swift file holds one string literal, a line per icon
(`name regular fill`, hex, `-` when a weight lacks the icon), which IconMap
parses once on first use: a dictionary literal of ~1500 entries would slow
down type checking with Swift 5.10.
"""

import json
import pathlib
import re
import sys

# vestal's own names for glyphs Phosphor shares between two meanings. They
# draw the same glyph from the icon font, but a renderer with native icons
# (macOS, theme.icons "native") can tell them apart: sunrise.fill and
# sunset.fill.
ALIASES = {"sunrise": "sun-horizon", "sunset": "sun-horizon"}

RULE = re.compile(r'\.ph(?:-fill)?\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)";\s*\}')


def parse(path):
    icons = {}
    for name, hex_code in RULE.findall(path.read_text(encoding="utf-8")):
        icons[name] = int(hex_code, 16)
    if not icons:
        sys.exit(f"gen-iconmap: no icons found in {path}")
    return icons


def main():
    root = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parent.parent
    icons_dir = root / "Resources" / "icons"
    regular = parse(icons_dir / "regular.css")
    fill = parse(icons_dir / "fill.css")
    names = sorted(set(regular) | set(fill))

    def hx(table, name):
        return format(table[name], "x") if name in table else "-"

    lines = "\n".join(f"{n} {hx(regular, n)} {hx(fill, n)}" for n in names)
    for alias, target in ALIASES.items():
        if alias in regular or alias in fill or target not in regular:
            sys.exit(f"gen-iconmap: alias {alias} -> {target} clashes or has no target")
    aliases = ", ".join(f'"{a}": "{t}"' for a, t in sorted(ALIASES.items()))
    out = f'''// Generated by nix/gen-iconmap.py from Resources/icons/{{regular,fill}}.css
// (Phosphor Icons 2.1.2). Do not edit; run `python3 nix/gen-iconmap.py`.

// MARK: - Icon map
//
// The bundled icon set's names and code points. A
// name is Phosphor's kebab-case name without the weight suffix; the render
// model sends it with the glyph of the requested weight, which a UI draws in
// the matching font (`Phosphor` for regular, `Phosphor-Fill` for fill).

public enum IconMap {{
    /// The weights vestal uses, in order.
    public static let weightNames = ["regular", "fill"]

    /// Every icon the built-in presets use.
    public static let presetIcons = [
        "clock", "hard-drives", "battery-full", "battery-high", "battery-medium", "battery-low", "battery-empty",
        "battery-charging", "hourglass", "arrow-down", "arrow-up", "microphone", "microphone-slash",
        "video-camera", "video-camera-slash", "play", "pause", "speaker-none", "speaker-low", "speaker-high",
        "speaker-x", "sunrise", "sunset", "circle",
    ]

    /// The glyph (a one-character string in the icon font) of `name` in
    /// `weight` (`regular` or `fill`); nil for an unknown name or weight,
    /// and for `sf:` names, which have no glyph.
    public static func glyph(_ name: String, weight: String) -> String? {{
        codePoint(name, weight: weight).flatMap(Unicode.Scalar.init).map {{ String(Character($0)) }}
    }}

    /// vestal's names for glyphs the set shares between two meanings: the
    /// same glyph here, told apart by native renderers (macOS draws
    /// `sunrise.fill` and `sunset.fill`). Not in `names`, which is the set's.
    public static let aliases: [String: String] = [{aliases}]

    /// The code point of `name` in `weight`; nil when there is none.
    public static func codePoint(_ name: String, weight: String) -> UInt32? {{
        guard let entry = entry(name) else {{ return nil }}
        switch weight {{
        case "regular": return entry.regular
        case "fill": return entry.fill
        default: return nil
        }}
    }}

    /// The weights `name` exists in (`regular`, `fill`); empty when unknown.
    public static func weights(_ name: String) -> [String] {{
        guard let entry = entry(name) else {{ return [] }}
        return (entry.regular != nil ? ["regular"] : []) + (entry.fill != nil ? ["fill"] : [])
    }}

    /// Whether the bundled set has an icon called `name`.
    public static func contains(_ name: String) -> Bool {{ entry(name) != nil }}

    /// Every icon name, sorted.
    public static var names: [String] {{ sortedNames }}

    // MARK: Table

    private struct Entry {{
        var regular: UInt32?
        var fill: UInt32?
    }}

    private static func entry(_ name: String) -> Entry? {{
        table[name] ?? aliases[name].flatMap {{ table[$0] }}
    }}

    private static let table: [String: Entry] = {{
        var table: [String: Entry] = [:]
        for line in data.split(separator: "\\n") {{
            let parts = line.split(separator: " ")
            guard parts.count == 3 else {{ continue }}
            table[String(parts[0])] = Entry(regular: UInt32(parts[1], radix: 16), fill: UInt32(parts[2], radix: 16))
        }}
        return table
    }}()

    private static let sortedNames: [String] = table.keys.sorted()

    /// How many icons the set has.
    static let count = {len(names)}

    /// `name regular fill`, hex code points (`-`: not in that weight).
    private static let data = """
{lines}
"""
}}
'''
    target = root / "Sources" / "VestalCore" / "Generated" / "IconMap.swift"
    target.write_text(out, encoding="utf-8")
    print(f"gen-iconmap: {len(names)} icons -> {target.relative_to(root)}")

    # The same table for the web renderer: name -> [regular, fill] code points
    # as hex strings (null where a weight lacks the icon), plus the aliases.
    rows = ",\n".join(
        f'  "{n}": [{json.dumps(hx(regular, n) if n in regular else None)}, {json.dumps(hx(fill, n) if n in fill else None)}]'
        for n in names
    )
    alias_rows = ", ".join(f'"{a}": "{t}"' for a, t in sorted(ALIASES.items()))
    js = f'''// Generated by nix/gen-iconmap.py from Resources/icons/{{regular,fill}}.css
// (Phosphor Icons 2.1.2). Do not edit; run `python3 nix/gen-iconmap.py`.

// name -> [regular, fill] code points in hex (null: not in that weight).
export const ICONS = {{
{rows}
}};

// vestal's names for glyphs the set shares between two meanings.
export const ALIASES = {{ {alias_rows} }};

/** The glyph (a one-character string) of `name` in `weight`, or null. */
export function glyphFor(name, weight = "regular") {{
  const entry = ICONS[name] || ICONS[ALIASES[name]];
  if (!entry) return null;
  const hex = entry[weight === "fill" ? 1 : 0];
  return hex ? String.fromCodePoint(parseInt(hex, 16)) : null;
}}
'''
    web_target = root / "web" / "renderer" / "icons.js"
    web_target.parent.mkdir(parents=True, exist_ok=True)
    web_target.write_text(js, encoding="utf-8")
    print(f"gen-iconmap: {len(names)} icons -> {web_target.relative_to(root)}")


if __name__ == "__main__":
    main()
