"""Embed the background shaders in the vestal binary.

The GTK renderer compiles the GLSL in Resources/shaders (common.glsl and one
body per background); the web renderer reads the same files. This turns them
into Sources/VestalCore/Generated/EmbeddedShaders.swift, one string literal
per file, so the binary needs no files at run time. The output is committed;
a test (ShaderTests) fails when it drifts from the files, so run this after
editing any of them.

usage: python3 nix/gen-shaders.py [repository root]   (default: the parent of nix/)
"""

import pathlib
import re
import sys

HEADER = """\
// Generated by nix/gen-shaders.py from Resources/shaders/*.glsl.
// Do not edit: change the GLSL and run `python3 nix/gen-shaders.py`.

/// The background shaders (GLSL ES 3.00 style), by file name without `.glsl`.
/// `common` is shared; the others each define `vec4 background()`.
public enum EmbeddedShaders {
    public static let sources: [String: String] = [
"""


def literal(text):
    """A Swift raw multi-line string literal whose value is exactly `text`."""
    runs = [len(m.group(1)) for m in re.finditer(r'(?:"""|\\)(#+)', text)]
    hashes = "#" * (max(runs, default=0) + 1)
    # The line break before the closing delimiter is not part of the value.
    return f'{hashes}"""\n{text}\n"""{hashes}'


def main():
    root = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parent.parent
    files = sorted((root / "Resources" / "shaders").glob("*.glsl"))
    out = [HEADER]
    for path in files:
        text = path.read_text(encoding="utf-8")
        if "\r" in text:
            sys.exit(f"{path}: carriage returns are not allowed")
        if not text.endswith("\n"):
            sys.exit(f"{path}: must end with a newline")
        out.append(f'        "{path.stem}": {literal(text)},\n')
    out.append("    ]\n}\n")
    target = root / "Sources" / "VestalCore" / "Generated" / "EmbeddedShaders.swift"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()
