"""Generate an XCTest entry point for a SwiftPM package's tests.

SwiftPM on Linux finds tests through the compiler's index store, which needs
the toolchain's libIndexStore. nixpkgs' Swift doesn't ship it, so `swift test`
fails there; given a Tests/LinuxMain.swift, SwiftPM runs that instead. The
`tests` flake check calls this on a copy of the source; nothing is committed.

usage: gen-linuxmain.py <Tests dir>

For each test target (a directory under Tests/), writes
<target>/__NixAllTests.swift with the target's test lists (inside the test
module, so internal test classes need no @testable import), then
Tests/LinuxMain.swift. Exits non-zero when a `func test...()` can't be tied to
a direct XCTestCase subclass, so a test these lists would miss fails the build
instead of being skipped.
"""

import pathlib
import re
import sys

ATTRS = r"(?:@\w+(?:\([^)]*\))?\s+)*"
CLASS = re.compile(r"^" + ATTRS + r"(?:(?:public|internal|open|final)\s+)*class\s+(\w+)\s*:\s*XCTestCase\b")
EXTENSION = re.compile(r"^" + ATTRS + r"(?:(?:public|internal)\s+)*extension\s+(\w+)\b")
TOP_LEVEL_TYPE = re.compile(
    r"^" + ATTRS + r"(?:(?:public|internal|private|fileprivate|open|final)\s+)*"
    r"(?:class|struct|enum|actor|protocol)\s+\w+"
)
TEST = re.compile(r"^\s+" + ATTRS + r"(?:(?:public|internal|open|override)\s+)*func\s+(test\w*)\s*\(\s*\)\s*(async\b)?")
HIDDEN_TEST = re.compile(r"^\s+" + ATTRS + r"(?:\w+\s+)*(?:private|fileprivate|static|class)\s+(?:\w+\s+)*func\s+test")
DIRECTIVE = re.compile(r"^\s*#(if|elseif|else|endif)\b\s*(.*?)\s*(?://.*)?$")

# Modules a Linux test build can import; any other canImport() is false.
LINUX_MODULES = {"Foundation", "FoundationNetworking", "FoundationXML", "Glibc", "Dispatch", "XCTest"}


def condition(text):
    """Evaluates a compilation condition as it holds on Linux. Anything this
    doesn't understand counts as true."""
    expr = re.sub(r"\bos\((\w+)\)", lambda m: str(m.group(1) == "Linux"), text)
    expr = re.sub(
        r"\bcanImport\(([\w.]+)\)",
        lambda m: str(m.group(1) in LINUX_MODULES or m.group(1).startswith("Vestal")),
        expr,
    )
    expr = re.sub(r"\b\w+\([^)]*\)", "True", expr)
    expr = expr.replace("&&", " and ").replace("||", " or ").replace("!", " not ")
    try:
        return bool(eval(expr, {"__builtins__": {}}, {"True": True, "False": False}))
    except Exception:
        return True


def scan(target):
    files = sorted(f for f in target.rglob("*.swift") if f.name != "__NixAllTests.swift")
    sources = {f: f.read_text().splitlines() for f in files}
    classes = {m.group(1) for lines in sources.values() for line in lines if (m := CLASS.match(line))}
    tests = {c: [] for c in classes}
    unattributed = []
    for f, lines in sources.items():
        current = None
        stack = []  # [active, taken] per open #if
        for n, line in enumerate(lines, 1):
            d = DIRECTIVE.match(line)
            if d:
                kind, cond = d.groups()
                if kind == "if":
                    active = condition(cond)
                    stack.append([active, active])
                elif kind == "elseif" and stack:
                    active = not stack[-1][1] and condition(cond)
                    stack[-1] = [active, stack[-1][1] or active]
                elif kind == "else" and stack:
                    stack[-1] = [not stack[-1][1], True]
                elif kind == "endif" and stack:
                    stack.pop()
                continue
            if not all(active for active, _ in stack):
                continue
            if m := CLASS.match(line):
                current = m.group(1)
            elif m := EXTENSION.match(line):
                current = m.group(1) if m.group(1) in classes else None
            elif TOP_LEVEL_TYPE.match(line):
                current = None
            elif HIDDEN_TEST.match(line):
                continue
            elif m := TEST.match(line):
                if current is None:
                    unattributed.append(f"{f}:{n}: {line.strip()}")
                else:
                    tests[current].append((m.group(1), m.group(2) is not None))
    return tests, unattributed


tests_dir = pathlib.Path(sys.argv[1])
imports, entries, problems, total = [], [], [], 0
for target in sorted(d for d in tests_dir.iterdir() if d.is_dir()):
    module = target.name
    tests, unattributed = scan(target)
    problems += unattributed
    classes = [c for c in sorted(tests) if tests[c]]
    if not classes:
        continue
    out = ["// Generated by nix/gen-linuxmain.py for the Nix `tests` check.", "import XCTest", ""]
    for c in classes:
        out.append(f"extension {c} {{")
        out.append(f"    static let __nixAllTests: [(String, ({c}) -> () throws -> Void)] = [")
        for name, is_async in tests[c]:
            out.append(f'        ("{name}", {f"asyncTest({name})" if is_async else name}),')
            total += 1
        out += ["    ]", "}", ""]
    out.append(f"public let __nixAllTests_{module}: [XCTestCaseEntry] = [")
    out += [f"    testCase({c}.__nixAllTests)," for c in classes]
    out.append("]")
    (target / "__NixAllTests.swift").write_text("\n".join(out) + "\n")
    imports.append(f"import {module}")
    entries.append(f"__nixAllTests_{module}")

if problems:
    sys.exit("gen-linuxmain: tests outside a direct XCTestCase subclass:\n  " + "\n  ".join(problems))
if not entries:
    sys.exit(f"gen-linuxmain: no tests under {tests_dir}")

(tests_dir / "LinuxMain.swift").write_text(
    "// Generated by nix/gen-linuxmain.py for the Nix `tests` check.\n"
    "import XCTest\n" + "\n".join(imports) + "\n\nXCTMain(" + " + ".join(entries) + ")\n"
)
print(f"gen-linuxmain: {total} tests in {len(entries)} target(s)")
