"""Generate Sources/VestalCore/Generated/IconMap.swift from the vendored
Phosphor metadata (Resources/icons/regular.css and fill.css).

usage: gen-iconmap.py [repo root]   (default: the parent of this script's directory)

Each CSS rule `.ph.ph-<name>:before { content: "\\eXXX"; }` (and
`.ph-fill.ph-<name>:before` in fill.css) gives an icon's code point in that
weight. The Swift file holds one string literal, a line per icon
(`name regular fill`, hex, `-` when a weight lacks the icon), which IconMap
parses once on first use: a dictionary literal of ~1500 entries would slow
down type checking with Swift 5.10.
"""

import pathlib
import re
import sys

RULE = re.compile(r'\.ph(?:-fill)?\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)";\s*\}')


def parse(path):
    icons = {}
    for name, hex_code in RULE.findall(path.read_text(encoding="utf-8")):
        icons[name] = int(hex_code, 16)
    if not icons:
        sys.exit(f"gen-iconmap: no icons found in {path}")
    return icons


def main():
    root = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parent.parent
    icons_dir = root / "Resources" / "icons"
    regular = parse(icons_dir / "regular.css")
    fill = parse(icons_dir / "fill.css")
    names = sorted(set(regular) | set(fill))

    def hx(table, name):
        return format(table[name], "x") if name in table else "-"

    lines = "\n".join(f"{n} {hx(regular, n)} {hx(fill, n)}" for n in names)
    out = f'''// Generated by nix/gen-iconmap.py from Resources/icons/{{regular,fill}}.css
// (Phosphor Icons 2.1.2). Do not edit; run `python3 nix/gen-iconmap.py`.

// MARK: - Icon map
//
// The bundled icon set's names and code points (EXTENSIBILITY.md §8.6). A
// name is Phosphor's kebab-case name without the weight suffix; the render
// model sends it with the glyph of the requested weight, which a UI draws in
// the matching font (`Phosphor` for regular, `Phosphor-Fill` for fill).

public enum IconMap {{
    /// The weights vestal uses, in order.
    public static let weightNames = ["regular", "fill"]

    /// Every icon the built-in presets use (docs/EXTENSIBILITY.md §8.6).
    public static let presetIcons = [
        "clock", "hard-drives", "battery-full", "battery-high", "battery-medium", "battery-low", "battery-empty",
        "battery-charging", "hourglass", "arrow-down", "arrow-up", "microphone", "microphone-slash",
        "video-camera", "video-camera-slash", "play", "pause", "speaker-none", "speaker-low", "speaker-high",
        "speaker-x", "sun-horizon", "circle",
    ]

    /// The glyph (a one-character string in the icon font) of `name` in
    /// `weight` (`regular` or `fill`); nil for an unknown name or weight,
    /// and for `sf:` names, which have no glyph.
    public static func glyph(_ name: String, weight: String) -> String? {{
        codePoint(name, weight: weight).flatMap(Unicode.Scalar.init).map {{ String(Character($0)) }}
    }}

    /// The code point of `name` in `weight`; nil when there is none.
    public static func codePoint(_ name: String, weight: String) -> UInt32? {{
        guard let entry = table[name] else {{ return nil }}
        switch weight {{
        case "regular": return entry.regular
        case "fill": return entry.fill
        default: return nil
        }}
    }}

    /// The weights `name` exists in (`regular`, `fill`); empty when unknown.
    public static func weights(_ name: String) -> [String] {{
        guard let entry = table[name] else {{ return [] }}
        return (entry.regular != nil ? ["regular"] : []) + (entry.fill != nil ? ["fill"] : [])
    }}

    /// Whether the bundled set has an icon called `name`.
    public static func contains(_ name: String) -> Bool {{ table[name] != nil }}

    /// Every icon name, sorted.
    public static var names: [String] {{ sortedNames }}

    // MARK: Table

    private struct Entry {{
        var regular: UInt32?
        var fill: UInt32?
    }}

    private static let table: [String: Entry] = {{
        var table: [String: Entry] = [:]
        for line in data.split(separator: "\\n") {{
            let parts = line.split(separator: " ")
            guard parts.count == 3 else {{ continue }}
            table[String(parts[0])] = Entry(regular: UInt32(parts[1], radix: 16), fill: UInt32(parts[2], radix: 16))
        }}
        return table
    }}()

    private static let sortedNames: [String] = table.keys.sorted()

    /// How many icons the set has.
    static let count = {len(names)}

    /// `name regular fill`, hex code points (`-`: not in that weight).
    private static let data = """
{lines}
"""
}}
'''
    target = root / "Sources" / "VestalCore" / "Generated" / "IconMap.swift"
    target.write_text(out, encoding="utf-8")
    print(f"gen-iconmap: {len(names)} icons -> {target.relative_to(root)}")


if __name__ == "__main__":
    main()
